language: python

python:
  - 3.6

install:
  - pip install flake8
  - sudo apt-get update -qq
  - sudo apt-get install -y python-dev libboost-dev
  - git submodule init
  - git submodule update

before_script:
  - flake8 .

env:
  - TASK=test
  - TASK=sdist

script:
  - cd pyQuantuccia
  - python setup.py $TASK

notifications:
  email: false
