language: python

install:
  - pip install flake8
  - sudo apt-get update -qq
  - sudo apt-get install -y python-dev

before_script:
  - flake8 .

script:
  - cd pyQuantuccia
  - python setup.py test
  - python setup.py sdist

notifications:
  email: false
