language: python

install:
  - pip install flake8
  - apt-get install python-dev

before_script:
  - flake8 .

script:
  - cd pyQuantuccia
  - python setup.py test
  - python setup.py sdist

notifications:
  email: false
